# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jobTemplate.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(365, 299)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.closeJobButton = QtGui.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeJobButton.setIcon(icon)
        self.closeJobButton.setObjectName(_fromUtf8("closeJobButton"))
        self.gridLayout.addWidget(self.closeJobButton, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.jobPlotFrame = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobPlotFrame.sizePolicy().hasHeightForWidth())
        self.jobPlotFrame.setSizePolicy(sizePolicy)
        self.jobPlotFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.jobPlotFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.jobPlotFrame.setObjectName(_fromUtf8("jobPlotFrame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.jobPlotFrame)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.headerTableWidget = QtGui.QTableWidget(self.jobPlotFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerTableWidget.sizePolicy().hasHeightForWidth())
        self.headerTableWidget.setSizePolicy(sizePolicy)
        self.headerTableWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.headerTableWidget.setObjectName(_fromUtf8("headerTableWidget"))
        self.headerTableWidget.setColumnCount(2)
        self.headerTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.headerTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.headerTableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_3.addWidget(self.headerTableWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.jobPlotFrame, 2, 0, 1, 3)
        self.jobProgressWidget = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobProgressWidget.sizePolicy().hasHeightForWidth())
        self.jobProgressWidget.setSizePolicy(sizePolicy)
        self.jobProgressWidget.setObjectName(_fromUtf8("jobProgressWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.jobProgressWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.progressBar = QtGui.QProgressBar(self.jobProgressWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 1, 1, 1, 1)
        self.cancelJobButton = QtGui.QPushButton(self.jobProgressWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelJobButton.setIcon(icon1)
        self.cancelJobButton.setObjectName(_fromUtf8("cancelJobButton"))
        self.gridLayout_2.addWidget(self.cancelJobButton, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.jobProgressWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.jobProgressWidget, 0, 0, 1, 3)
        self.runtimeWidget = QtGui.QWidget(Form)
        self.runtimeWidget.setObjectName(_fromUtf8("runtimeWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.runtimeWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.runtimeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.initTimeLabel = QtGui.QLabel(self.runtimeWidget)
        self.initTimeLabel.setObjectName(_fromUtf8("initTimeLabel"))
        self.horizontalLayout_2.addWidget(self.initTimeLabel)
        self.label_6 = QtGui.QLabel(self.runtimeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.runTimeLabel = QtGui.QLabel(self.runtimeWidget)
        self.runTimeLabel.setObjectName(_fromUtf8("runTimeLabel"))
        self.horizontalLayout_2.addWidget(self.runTimeLabel)
        spacerItem1 = QtGui.QSpacerItem(37, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addWidget(self.runtimeWidget, 1, 0, 1, 3)
        self.toggleMetadataButton = QtGui.QPushButton(Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/expert_mode.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleMetadataButton.setIcon(icon2)
        self.toggleMetadataButton.setCheckable(True)
        self.toggleMetadataButton.setChecked(False)
        self.toggleMetadataButton.setObjectName(_fromUtf8("toggleMetadataButton"))
        self.gridLayout.addWidget(self.toggleMetadataButton, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.cancelJobButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.cancelJob)
        QtCore.QObject.connect(self.closeJobButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.closeJob)
        QtCore.QObject.connect(self.toggleMetadataButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.headerTableWidget.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.closeJobButton.setToolTip(_translate("Form", "Close job tab", None))
        self.closeJobButton.setText(_translate("Form", "Close job", None))
        item = self.headerTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Header", None))
        item = self.headerTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Value", None))
        self.cancelJobButton.setToolTip(_translate("Form", "Cancel runnin gjob", None))
        self.cancelJobButton.setText(_translate("Form", "Cancel job", None))
        self.label_10.setText(_translate("Form", "Runtime countdown:", None))
        self.label_2.setText(_translate("Form", "Init time:", None))
        self.initTimeLabel.setText(_translate("Form", "xxxx-xx-xx xx:xx:xx", None))
        self.label_6.setText(_translate("Form", "Runtime:", None))
        self.runTimeLabel.setText(_translate("Form", "None", None))
        self.toggleMetadataButton.setText(_translate("Form", "Toggle metadata", None))

import resources_rc
